### ISSUE TITLE
Details on the release date

### ISSUE THREAD

**Issue by tristandeborde** [DiT-3D/DiT-3D#1]
Hello,

And thanks for the great work and very interesting paper! 

I'm currently toying with 3d voxel object generation and I want to replace my 3dconv models with DiT-3D to see if it improves performance.
I was wondering if the released date is planned soon (a few days/ 1 or 2 weeks) or if I should start working on my own implem right now 😅 As far as I'm concerned, just the bare model code alone (DiT-3D block) would be very useful for my project! This would allow me to plug the DiT-3D block in my architecture.

Anyways, I'm very grateful for the work
Cheers

**Comment by DiT-3D** [comment]
Hi,

Thanks for your interest in our work. We have released our code now.
