### ISSUE TITLE
environment problem

### ISSUE THREAD

**Issue by amannier** [DiT-3D/DiT-3D#10]
When I run test.py,anaconda prompt shows the error: subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.,how can I solve this problem? I have already installed ninja.

**Comment by vgthengane** [comment]
check this out - https://github.com/pytorch/vision/issues/2360#issuecomment-883574291

**Comment by vgthengane** [comment]
in cpp_extension.py file of pytorch, lok for  `['ninja', '-v']` and change it to `['ninja', '-version']`.

**Comment by amannier** [comment]
Thank you for your reply, but changing - v to -- version is the method I have tried and still haven't resolved the error。

**Comment by amannier** [comment]
<img width="1270" alt="屏幕截图 2024-03-28 233249" src="https://github.com/DiT-3D/DiT-3D/assets/160259274/3fd268d7-0751-4612-8e7d-f2acd735d5ec">
This is a screenshot of the error message. Could you please help me check if I misunderstood it？

**Comment by vgthengane** [comment]
Sorry, the image is not getting loaded on my side.

**Comment by amannier** [comment]
[https://github.com/amannier/My-Image/blob/main/ninja_error.png](url)
Sorry, I have not uploaded a image to Github before. What about this time?

**Comment by amannier** [comment]
[https://github.com/amannier/My-Image/blob/main/ninja_error.png](url)
Sorry, I have not uploaded the image to Github before. What about this time?

**Comment by amannier** [comment]
It seems that this link needs to be copied to a new webpage for successful access. Excuse me.

**Comment by vgthengane** [comment]
> in cpp_extension.py file of pytorch, look for `['ninja', '-v']` and change it to `['ninja', '--version']`.

this should be done in pytorch library. (follow this for detailed explaination - https://github.com/pytorch/vision/issues/2360#issuecomment-883574291)

**Comment by gsfsdv** [comment]
My solution is to replace the last line of setup.py with
 cmdclass={
        'build_ext': BuildExtension.with_options(use_ninja=False)
    })

If there is an error about THCudaCheck(cudaGetLastError()) in emd_kernerl.cu, replace it with AT_CUDA_CHECK(cudaGetLastError());

And comment out all CHECK_EQ() functions

**Comment by DDgogogo** [comment]
> check this out - [pytorch/vision#2360 (comment)](https://github.com/pytorch/vision/issues/2360#issuecomment-883574291)

I set the path in the parameter parser.add_argument('-- model', default='continue/epoch_999.pth', help=" path to model (to continue training)") and set the parameter '--distribution_type' to single, and I get the following error The following error was reported:

Traceback (most recent call last):
  File "train.py", line 929, in <module>
    main()
  File "train.py", line 844, in main
    train(opt.gpu, opt, output_dir, noises_init)
  File "train.py", line 817, in train
    dist.destroy_process_group()
  File "/home/vipuser/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 573, in destroy_process_group
    raise RuntimeError("Invalid process group specified")
RuntimeError: Invalid process group specified
can you help me?

**Comment by DiT-3D** [comment]
@vgthengane @gsfsdv Thanks for your help. @DDgogogo Please try to follow README and set up the PyTorch environment properly.
