### ISSUE TITLE
Long compilation time when installing PyTorchEMD

### ISSUE THREAD

**Issue by QihanZhao** [DiT-3D/DiT-3D#12]
## Environment

- OS: [e.g., Ubuntu 20.04]
- GCC version: 8.5.0 20210514 (Red Hat 8.5.0-18)
- NVCC version: 10.1
- Others: followed your instruction 

## Issue Description

I tried to install PyTorchEMD on my system, but the compilation process is taking a very long time. I ran the following commands:

```bash
cd metrics/PyTorchEMD
python setup.py install
```

The `python setup.py install` step is particularly slow. Is there any way to speed up the compilation process or any pre-built binaries available?

![1da09fbc5032252fcbae6bed50767fff](https://github.com/DiT-3D/DiT-3D/assets/94861831/04e0c505-671f-41c5-830f-a539ab77905b)

## Expected Behavior

I expected the compilation process to be relatively quick, or at least have some indication of progress or estimated time to completion.

## Actual Behavior

The installation process takes an unusually long time with no clear indication as to why it's taking so long or how much longer it will take.

Any advice or solutions would be greatly appreciated!

**Comment by DiT-3D** [comment]
Please try to follow README and set up the PyTorch environment properly. Meanwhile, you can post issues in the original PyTorchEMD [repo](https://github.com/daerduoCarey/PyTorchEMD) for any help.
