### ISSUE TITLE
Question about Voxelization Module

### ISSUE THREAD

**Issue by sIHURs** [DiT-3D/DiT-3D#17]
Hi，

In your code, there is a modules-folder that appears to be from PVcnn (maybe?). Can the voxelization process within this modules be replaced by other Python libraries? Is the purpose of using this modules to perform voxelization on the GPU to accelerate training or inference speed, or are there other considerations?

Additionally, thank you very much for your research. It is truly excellent.

Yifan

**Comment by DiT-3D** [comment]
Hi Yifan, thanks for your interest in our work! The voxelization process can be replaced by other Cuda-based Python libraries for accelerating training or inference speed.
