### ISSUE TITLE
About Training Time

### ISSUE THREAD

**Issue by JudgeLJX** [DiT-3D/DiT-3D#21]
HI, thanks for your contribution.

Could you please clarify whether the "training hours" mentioned in Table 2 refers to actual elapsed time rather than GPU hours? If it is indeed the real training hours, does that mean that training on a single card would require 32-64 times the mentioned duration, considering you used 32-64 V100 GPUs for the training?

Best

**Comment by DiT-3D** [comment]
Hi, thanks for your interest in our work. Your understanding is correct.
