### ISSUE TITLE
About Transformer Structure

### ISSUE THREAD

**Issue by Litoda** [DiT-3D/DiT-3D#22]
Hello Sir,
Could you explain why you chose to expand the classical 2D diffusion transformer with voxelized input instead of using the PointTransformer v1/v2 structure? Are there specific disadvantages or limitations that make PTV1/2 less suitable for point cloud data?
Thanks very much!!!

**Comment by DiT-3D** [comment]
Hi, thanks for your interest in our work! There are no specific limitations that make PTV1/2 less suitable for point cloud data than 2D diffusion transformer with voxelized input. But it would be interesting to see those comparisons for future work.
