### ISSUE TITLE
How to get the best model during training？

### ISSUE THREAD

**Issue by Jack171516** [DiT-3D/DiT-3D#23]
Hello, sir, thanks for your great work, I always have a question, how do you get the best model during training? You say in the repository that you train 10,000 epochs for each class and then save a model every 25 epochs, is it possible to get the best model after training by evaluating the saved models one by one? If so, it seems like it would take a lot of time. Can you answer this question? Thank you very much.

**Comment by DiT-3D** [comment]
Hi, thanks for your interest in our work! We evaluated those saved checkpoints after training.
