### ISSUE TITLE
Probable mistake in window_partition function

### ISSUE THREAD

**Issue by dongyf43** [DiT-3D/DiT-3D#24]
Thanks for your code. I noticed a probable mistake but I am not sure. In `window_partition` function:
```
def window_partition(x, window_size):
    B, X, Y, Z, C = x.shape
    pad_x = (window_size - X % window_size) % window_size
    pad_y = (window_size - Y % window_size) % window_size
    pad_z = (window_size - Z % window_size) % window_size
    if pad_x > 0 or pad_y > 0 or pad_z > 0:
        x = F.pad(x, (0, 0, 0, pad_x, 0, pad_y))
    Xp, Yp, Zp = X + pad_x, Y + pad_y, Z + pad_z
    x = x.view(B, Xp // window_size, window_size, Yp // window_size, window_size, Zp // window_size, window_size, C)
    windows = x.permute(0, 1, 3, 5, 2, 4, 6, 7).contiguous().view(-1, window_size, window_size, window_size, C)
    return windows, (Xp, Yp, Zp)
```
The variable `pad_z` was not used in `x = F.pad(x, (0, 0, 0, pad_x, 0, pad_y))`, which may cause an error (shape mismatch) when doing `x = x.view(B, Xp // window_size, window_size, Yp // window_size, window_size, Zp // window_size, window_size, C)`.

**Comment by DiT-3D** [comment]
Hi, thanks for your interest! Please refer to the details about the window attention operation in the [ViTDet](https://arxiv.org/abs/2203.16527) paper.
