### ISSUE TITLE
Question about environment

### ISSUE THREAD

**Issue by KyujinHan** [DiT-3D/DiT-3D#25]
Thanks for your repo..!  
I wonder, this repo only can implement with `Pytorch==1.7.1`??  
  
![image](https://github.com/user-attachments/assets/5bf1f085-59ef-4d4a-a936-b9a800fca71f)
When I used pytorch `2.1.0 & 1.12.1`, I think the code is not working..😭  
(The error code means that there is no file: **`_pvcnn_backend.so`**)  
  
Is there any solution..?   
Thanks.

**Comment by DiT-3D** [comment]
Hi, thanks for your interest in our work! Our current codebase supports `1.7.1` due to some conflict package version. Please feel free to ask for help from these original works when it comes to package installation.

**Comment by minkyujeon** [comment]
Hello @DiT-3D, you mentioned that there are some conflicting package versions. Could you let me know which ones are causing issues?
I'm only able to use PyTorch version 2.0 or newer. In this case, how can I run the code?
