### ISSUE TITLE
Paper Results

### ISSUE THREAD

**Issue by matteo-bastico** [DiT-3D/DiT-3D#26]
Hello, thank you for the amazing work! Are the results in Table 1 of the paper obtained with a model trained on the three category simultaneously? And results in Table 4c are referring to which category?  I initially thought it was the average of the three but then it does not correspond to Table 1 (for the XL model). Thank you in advance !

**Comment by DiT-3D** [comment]
Hi, thanks for your interest in our work. Table 1 reports the model trained on each class for comparison with previous work. Table 4c refers to the results trained on three classes.
