### ISSUE TITLE
PyTorchEMD compiling error

### ISSUE THREAD

**Issue by Wanghc233** [DiT-3D/DiT-3D#3]
I have used anaconda to create the virtual space to run this project, while compiling PyTorchEMD I am facing the following problem, but my linux system is softwired with cuda11, how can I fix it, looking forward to your answer!

FAILED: /home/XXX/DiT-3D/metrics/PyTorchEMD/build/temp.linux-x86_64-3.6/cuda/emd_kernel.o 
/usr/local/cuda-11.0/bin/nvcc -I/home/whc/miniconda3/envs/dy/lib/python3.6/site-packages/torch/include -I/home/whc/miniconda3/envs/dy/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/whc/miniconda3/envs/dy/lib/python3.6/site-packages/torch/include/TH -I/home/whc/miniconda3/envs/dy/lib/python3.6/site-packages/torch/include/THC -I/usr/local/cuda-11.0/include -I/home/whc/miniconda3/envs/dy/include/python3.6m -c -c /home/whc/DiT-3D/metrics/PyTorchEMD/cuda/emd_kernel.cu -o /home/whc/DiT-3D/metrics/PyTorchEMD/build/temp.linux-x86_64-3.6/cuda/emd_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=emd_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_86,code=sm_86 -std=c++14
nvcc fatal   : Unsupported gpu architecture 'compute_86'

**Comment by DiT-3D** [comment]
Hi, we do not have this error before. Maybe you can check [this repo](https://github.com/daerduoCarey/PyTorchEMD/tree/master) for reference. Also please make sure you follow the steps we provided to install PyTorchEMD.
