### ISSUE TITLE
About num_classes argument

### ISSUE THREAD

**Issue by ardianumam** [DiT-3D/DiT-3D#5]
Hi,

I have inquire about the `num_classes` argument. 
1. If I we train single category, e.g., chair category, in the `train.py`, should we set `num_classes=1`? 
2. The default value for `num_classes` in `train.py` is 55, so after training and testing the trained model, I got the error below (due to different default values of `num_classes`, 55 and 1 in `train.py` and `test.py`, respectively). After I change `num_classes=55` in `test.py`, I got no error. Although it worked and got no error, I wonder if setting `num_classes=55` for single class generation will impact (probably lower) the performance compared to if we set `num_classes=1`. Could you elaborate on this?

Many thanks!

Error mentioned in no 2
```
size mismatch for model.module.y_embedder.embedding_table.weight: copying a param with shape torch.Size([56, 768]) from checkpoint, the shape in current model is torch.Size([2, 768]).
```

**Comment by whocares387** [comment]
I have encountered the same problem.

**Comment by m-violet-s** [comment]
Hello, I would like to know if there is any progress on this issue?

**Comment by DiT-3D** [comment]
Hi, thanks for your interest! Please set the argument `--num_classes=1` for single category training, and also need to remember the argument `--category chair`.

**Comment by Lucarqi** [comment]
@DiT-3D @ardianumam I have two more questions:  
1) What does the `synsetid_to_cate` dictionary mean? Does the "key" represent the ID of a category in ImageNet?  
2) My task is to generate a type of 3D medical image. How should I set `class_num` and `--category`? Should I create a new ID?
