### ISSUE TITLE
Model parameter issues

### ISSUE THREAD

**Issue by m-violet-s** [DiT-3D/DiT-3D#8]
Hi, I have some questions about this part of the training code
`    if opt.category == 'airplane': `
`        opt.beta_start = 1e-5`
`        opt.beta_end = 0.008`
`        opt.schedule_type = 'warm0.1'`
During the training of the airplane class, the relevant parameters were modified here. Is it through comparison of experimental results that these parameters are more suitable?
If it's convenient, can you tell me the reason for trying this?

**Comment by DiT-3D** [comment]
Thanks for the question. We followed [PVD](https://github.com/alexzhou907/PVD) and used the same hyperparameters for training the airplane class. Please refer to the PVD repo for more details.
