### ISSUE TITLE
About the environment

### ISSUE THREAD

**Issue by DDgogogo** [DiT-3D/DiT-3D#9]
When I run test.py, why does it stop？
```
Jitting Chamfer 3D
Loaded JIT 3D CUDA chamfer distance
Random Seed:  42
grid_size: 8
2024-03-27 18:09:57,042 : Resume Path:checkpoint/checkpoint.pth
(base) root@ubuntu1804:~/DiT-3D# 
```
I run with python test.py --dataroot data/ShapeNetCore.v2.PC15k/    --category chair     --model_type 'DiT-S/4'     --voxel_size 32     --model checkpoint/checkpoint.pth

**Comment by DDgogogo** [comment]
I'm using a 4090 card, may I ask what your device is?

**Comment by vgthengane** [comment]
You have to provide `--generate` to generate images and `--eval_gen` to evaluate the generate results.

**Comment by DDgogogo** [comment]
> You must provide methods for `--generate` to generate images and `--eval_gen` to evaluate the results.

Thanks. The default is False, do I need to change both to True?

**Comment by amannier** [comment]
When I run test.py,anaconda prompt shows the error: subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.,how can I solve this problem? I have already installed ninja.

**Comment by vgthengane** [comment]
Yes, the bash command will look as following:
```

python eval.py \
    --dataroot $DATASET_DIR \
    --category chair \
    --model_dir $EXPERIMENT_DIR \
    --experiment_name $EXPERIMENT_NAME \
    --model_type 'DiT-S/4' \
    --voxel_size 32 \
    --model pre_trained_weights.pth \
    --generate \ # To generate samples
    --eval_gen \ # To evaluate generated samples
```

I hope this helps :)
